import { waLink, WA_MESSAGES } from "@/lib/site";
const questions = [
  ["¿Qué niveles educativos ofrece el colegio?", "Preescolar, primaria y secundaria. En la sección de niveles puedes conocer el enfoque de cada etapa y solicitar información específica para el grado que buscas."],
  ["¿Cómo puedo agendar una visita?", "Usa el botón Agenda una visita para contactar al colegio por WhatsApp. Indica el nivel de tu interés y acuerda la fecha y hora con el equipo antes de acudir."],
  ["¿Cuáles son los horarios, costos y requisitos de inscripción?", "Solicita al colegio la información del grado y ciclo que te interesa: horario de clases, fechas, documentos, inscripción y colegiatura. Pide también el desglose de materiales, uniformes y actividades, para saber qué incluye cada concepto."],
  ["¿Cómo consulto las becas y promociones?", "Contacta al colegio para confirmar vigencia, disponibilidad, requisitos, duración y compatibilidad de los apoyos publicados. Pregunta sobre qué concepto se aplica cada beneficio y cómo se renueva. La consulta no implica la asignación de una beca."],
  ["¿Qué debo preguntar sobre inglés y Cambridge?", "El colegio presenta inglés y certificaciones Cambridge dentro de su oferta. Consulta qué preparación corresponde al nivel de tu hijo o hija, qué exámenes están disponibles y si evaluación, materiales o certificaciones tienen un costo adicional."],
  ["¿Las imágenes de las actividades son fotografías de alumnos?", "Las imágenes de la sección de talleres fueron generadas con inteligencia artificial para ilustrar cada actividad; no son fotografías de alumnos del colegio. La fotografía de la fachada muestra el plantel."],
];
export default function FaqSection() {
  return <section id="preguntas" className="bg-white py-20 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-[0.75fr_1.25fr]"><div><h2 className="font-display text-3xl font-extrabold text-blue-dark sm:text-5xl">Resuelve tus dudas antes de visitarnos.</h2><p className="mt-5 leading-relaxed text-muted">La información que necesitas para dar el siguiente paso con tranquilidad.</p><a href={waLink(WA_MESSAGES.informes)} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex min-h-11 items-center font-bold text-blue underline underline-offset-4">Habla con el colegio</a></div><div className="divide-y divide-silver border-y border-silver">{questions.map(([q,a]) => <details key={q} className="faq-item py-1"><summary className="cursor-pointer py-5 pr-4 font-display text-lg font-semibold text-blue-dark">{q}</summary><p className="max-w-prose pb-6 pr-5 text-base leading-relaxed text-muted">{a}</p></details>)}</div></div></section>;
}
